server:
  port: 8099    #设置端口号

spring:
  datasource:
    username: OWPOIMP
    password: Pass1234
    url: jdbc:oracle:thin:@10.245.39.139:1522:covisint
    driver-class-name: oracle.jdbc.driver.OracleDriver

  data:
    elasticsearch:
      client:
        reactive:
          username: elasticsearch
          password:
          endpoints: 10.245.38.39:9200


# 配置mybatis-plus
mybatis-plus:
  # 配置mapper.xml文件存放的位置，当Mapper文件跟对应的Mapper接口处于同一位置的时候可以不用指定该属性的值
  mapper-locations: classpath:mapper/*.xml
  check-config-location: true
#  config-location: classpath:mybatis-config.xml   #设置mybatis的配置文件位置（报错）
  type-aliases-package: com.opentext.poi.entity   #设置别名包
  # 配置主键生成策略
  global-config:
    db-config:
      # 主键类型  auto:"数据库ID自增",INPUT:"用户输入ID",ASSIGN_ID:"分配ID",ASSIGN_UUID:"分配UUID";
      id-type: auto
      # 字段策略 FieldStrategy:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      select-strategy: NOT_EMPTY
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: null
    default-fetch-size: 100
    cache-enabled: true


logging:
  level:
    com:
      opentext:
        poi:
          mapper: debug   # Log4j建议只使用四个级别，优先级从高到低分别是 ERROR、WARN、INFO、DEBUG，粒度从粗到细